name: Changesets
on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code repository
        uses: actions/checkout@v2

      - name: Set up pnpm
        uses: pnpm/action-setup@v2

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Set safe directory
        shell: bash
        run: git config --global --add safe.directory "$(pwd)"

      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm version
          commit: "Update versions"
          title: "Update versions and publish"
          publish: pnpm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}